# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkslips', '0012_auto_20180303_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='latitude',
            field=models.FloatField(default=121.031851),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='latitude2',
            field=models.FloatField(default=121.057307),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='longitude',
            field=models.FloatField(default=14.652723),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='longitude2',
            field=models.FloatField(default=14.605568),
        ),
    ]
